services:
  web:
    build: .
    command: >
      sh -c "
        if [ -f /app/backup/db.sqlite3.backup ]; then
          echo 'Restoring database from backup...'
          cp /app/backup/db.sqlite3.backup /app/db.sqlite3
          chown appuser:appuser /app/db.sqlite3
        fi &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 solo_todo.wsgi:application
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sqlite_data:/app
      - ./backup:/app/backup:ro
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=your-super-secret-key-here-change-this
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,todo.emikon.rs,www.todo.emikon.rs,185.119.90.175
      - DB_ENGINE=sqlite3
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  sqlite_data:
