# Generated by Django 5.2.5 on 2025-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority order for sorting (lower number = higher priority)'),
        ),
    ]
