# Generated by Django 5.2.5 on 2025-08-22 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='savedfilter',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskdependency',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='taskdependency',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taskrelationship',
            options={},
        ),
        migrations.RemoveField(
            model_name='focussession',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='taskrelationship',
            name='description',
        ),
        migrations.AlterField(
            model_name='focussession',
            name='kind',
            field=models.CharField(choices=[('work', 'Work'), ('break', 'Break')], default='work', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('blocks', 'Blocks'), ('depends_on', 'Depends On'), ('subtask_of', 'Subtask Of'), ('related_to', 'Related To')], max_length=20),
        ),
        migrations.CreateModel(
            name='CalendarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('calendar_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task', 'calendar_date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, help_text='Cron-like pattern for recurring events', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Lunch Break, Coffee Break', max_length=100)),
                ('start_time', models.TimeField(help_text='Start time (e.g., 12:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 13:00)')),
                ('days_of_week', models.JSONField(default=list, help_text='List of days (0=Monday, 6=Sunday)')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='LinkAttachment',
        ),
        migrations.DeleteModel(
            name='SavedFilter',
        ),
        migrations.DeleteModel(
            name='TaskDependency',
        ),
    ]
