# Generated by Django 4.2.10 on 2025-08-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for recurring events', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_occurrences',
            field=models.IntegerField(blank=True, help_text='Maximum number of occurrences', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_interval',
            field=models.IntegerField(default=1, help_text='Every X days/weeks/months/years'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='weekdays',
            field=models.JSONField(default=list, help_text='List of weekdays for weekly recurrence (0=Monday, 6=Sunday)'),
        ),
    ]
